### ISSUE TITLE
InvalidDefinition error in step functions during deployment

### ISSUE THREAD

**Issue by andresionek91** [CloudSnorkel/cdk-github-runners#434]
Tried with versions `0.11.3`, `0.10.8` and `0.9.8`

My cdk version is:  2.96.2 (build 3edd240)

The stack synth happens correctly, but the deployment fails with the following:

```
UPDATE_FAILED        | AWS::StepFunctions::StateMachine | RunnersRunnerOrchestrator24222526
Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: These fields are required: [Choices] at /States/Run Providers/Branches[0]/States/Error Handler/Branches[0]/States/Choose provider' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: f57e11e2-0e6f-4d64-95be-0d99bd7632b5; Proxy: null)"
(RequestToken: 36b9f3da-6251-3315-87dd-409cac834382, HandlerErrorCode: InvalidRequest)


 ❌  GithubRunners-Root failed: Error: The stack named GithubRunners-Root failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "Invalid State Machine Definition: 'SCHEMA_VALIDATION_FAILED: These fields are required: [Choices] at /States/Run Providers/Branches[0]/States/Error Handler/Branches[0]/States/Choose provider' (Service: AWSStepFunctions; Status Code: 400; Error Code: InvalidDefinition; Request ID: f57e11e2-0e6f-4d64-95be-0d99bd7632b5; Proxy: null)" (RequestToken: 36b9f3da-6251-3315-87dd-409cac834382, HandlerErrorCode: InvalidRequest)
    at FullCloudFormationDeployment.monitorDeployment (/usr/local/lib/node_modules/aws-cdk/lib/index.js:443:10232)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/usr/local/lib/node_modules/aws-cdk/lib/index.js:446:153546)
    at async /usr/local/lib/node_modules/aws-cdk/lib/index.js:446:136809
```

Tried downgrading my cdk to aws-cdk-lib (2.97.0 -> 2.82.0), but still the same error happens.

This is the rendered resource in the stack:
```
  "RunnersRunnerOrchestrator24222526": {
   "Type": "AWS::StepFunctions::StateMachine",
   "Properties": {
    "RoleArn": {
     "Fn::GetAtt": [
      "RunnersRunnerOrchestratorRole5EB585E0",
      "Arn"
     ]
    },
    "DefinitionString": {
     "Fn::Join": [
      "",
      [
       "{\"StartAt\":\"Queue Idle Reaper\",\"States\":{\"Queue Idle Reaper\":{\"Next\":\"Run Providers\",\"Type\":\"Task\",\"ResultPath\":null,\"Resource\":\"arn:",
       {
        "Ref": "AWS::Partition"
       },
       ":states:::sqs:sendMessage\",\"Parameters\":{\"QueueUrl\":\"",
       {
        "Ref": "RunnersIdleReaperQueue6F3F714D"
       },
       "\",\"MessageBody\":{\"executionArn.$\":\"$$.Execution.Id\",\"runnerName.$\":\"$$.Execution.Name\",\"owner.$\":\"$.owner\",\"repo.$\":\"$.repo\",\"installationId.$\":\"$.installationId\",\"maxIdleSeconds\":600}}},\"Run Providers\":{\"Type\":\"Parallel\",\"End\":true,\"Retry\":[{\"ErrorEquals\":[\"States.ALL\"],\"IntervalSeconds\":60,\"MaxAttempts\":23,\"BackoffRate\":1.3}],\"Branches\":[{\"StartAt\":\"Error Handler\",\"States\":{\"Error Handler\":{\"Type\":\"Parallel\",\"End\":true,\"Catch\":[{\"ErrorEquals\":[\"States.ALL\"],\"ResultPath\":\"$.error\",\"Next\":\"Delete Failed Runner\"}],\"Branches\":[{\"StartAt\":\"Get Runner Token\",\"States\":{\"Get Runner Token\":{\"Next\":\"Choose provider\",\"Retry\":[{\"ErrorEquals\":[\"Lambda.ServiceException\",\"Lambda.AWSLambdaException\",\"Lambda.SdkClientException\"],\"IntervalSeconds\":2,\"MaxAttempts\":6,\"BackoffRate\":2}],\"Type\":\"Task\",\"ResultPath\":\"$.runner\",\"Resource\":\"",
       {
        "Fn::GetAtt": [
         "Runnerstokenretriever9569B60F",
         "Arn"
        ]
       },
       "\"},\"Choose provider\":{\"Type\":\"Choice\",\"Default\":\"Unknown label\"},\"Unknown label\":{\"Type\":\"Succeed\"}}}]},\"Delete Failed Runner\":{\"End\":true,\"Retry\":[{\"ErrorEquals\":[\"Lambda.ServiceException\",\"Lambda.AWSLambdaException\",\"Lambda.SdkClientException\"],\"IntervalSeconds\":2,\"MaxAttempts\":6,\"BackoffRate\":2},{\"ErrorEquals\":[\"RunnerBusy\"],\"IntervalSeconds\":60,\"MaxAttempts\":60,\"BackoffRate\":1}],\"Type\":\"Task\",\"ResultPath\":\"$.delete\",\"Resource\":\"",
       {
        "Fn::GetAtt": [
         "RunnersdeleterunnerE29F95CE",
         "Arn"
        ]
       },
       "\",\"Parameters\":{\"runnerName.$\":\"$$.Execution.Name\",\"owner.$\":\"$.owner\",\"repo.$\":\"$.repo\",\"installationId.$\":\"$.installationId\",\"error.$\":\"$.error\"}}}}]}}}"
      ]
     ]
    },
   "DependsOn": [
    "RunnersRunnerOrchestratorRoleDefaultPolicyE4928264",
    "RunnersRunnerOrchestratorRole5EB585E0"
   ],
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "GithubRunners-Root/Runners/Runner Orchestrator/Resource"
   }
  },

```

**Comment by andresionek91** [comment]
Issue with my code.
